---
- name: Create a directory if directory deos not exist
  ansible.builtin.file:
    path: "~/{{ item }}"
    state: directory
  loop: "{{ create_dirs }}"

- name: Set DNS Server
  ansible.builtin.command: "networksetup -setdnsservers Wi-Fi {{ dns_server | join(' ') }}"
  become: true
  changed_when: false

- name: Remove file (delete file)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ localized_files }}"
  become: true

- name: Set OSX defaults
  community.general.osx_defaults:
    domain: "{{ item.domain | default(omit) }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop: "{{ osx_settings }}"

# dictに対応していないので諦めてコマンドで
# https://github.com/ansible-collections/community.general/blob/main/plugins/modules/system/osx_defaults.py#L373
- name: Disable hotkeys
  ansible.builtin.command: defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add {{ item.key }} "{ enabled = 0; value = { parameters = ({{ item.value }}); type = 'standard'; }; }"
  loop: '{{ disable_hotkeys }}'
  notify: Apply setting
