homebrew_cask_packages:
  # Browsers
  - homebrew/cask-versions/firefox-developer-edition
  - google-chrome
#  - microsoft-edge # M1未対応

  # Develop
  - boost-note # next version
  - dash
  - iterm2
  - postico
  - sequel-pro
  - tableplus
  - sublime-text
  - jetbrains-toolbox
  - visual-studio-code
  - ngrok
  # - adobe-creative-cloud # M1まだない
  - firebase-admin
  # - google-cloud-sdk # M1まだない
  - postman
  - responsively
  - screaming-frog-seo-spider

  # Media
  - kindle
  - spotify
  - vlc
  # - guitar-pro # M1未対応
  - soundflowerbed

  # Tool
  - alfred
  # dockerはまだM1がプレピュー版しかない
  #- docker
  #- docker-toolbox
  - dropbox
  - google-backup-and-sync
  #- wireshark # M1未対応
  - rectangle
  - cleanshot
  - deepl
  - lastpass
  - sip
  - transmission
  - pixelsnap
  - microsoft-office
  #- cloudflare-warp # M1未対応
  - notion

  # Communication
  - discord
  - slack
  - linear-linear

  # Quicklook
  # https://github.com/sindresorhus/quick-look-plugins
  - apparency
  - betterzip
  - provisionql
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlstephen
  #- qlvideo # M1未対応
  - quicklook-csv
  - quicklook-json
  #- quicklook-pat # M1未対応
  - quicklookapk
  - quicklookase
  - webpquicklook
