---
- name: Install casks
  community.general.homebrew_cask:
    name: "{{ homebrew_cask_packages }}"
    state: present
    install_options: 'appdir=/Applications'

- name: Upgrade all casks
  community.general.homebrew_cask:
    upgrade_all: true
