---
- name: Tap homebrew caskroom/cask
  homebrew_tap:
    tap: "caskroom/cask"
    state: present
  become: false

- name: Update homebrew itself first
  homebrew:
    state: latest
    update_homebrew: yes
  become: false

- name: Install and upgrade homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  # GUIのインストール場所を/Applicationsにする
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  with_items: "{{ homebrew_cask_packages }}"
  when: homebrew_cask_packages
  become: false