---
# Install packages
- name: update homebrew
  homebrew:
    state: latest
    update_homebrew: yes
  become: false

- name: Add homebrew taps
  homebrew_tap:
    name: "{{ homebrew_taps }}"
    state: present
  become: false

- name: Install homebrew packages
  homebrew:
    name: "{{ homebrew_packages }}"
    state: latest
  become: false
