---
- name: Ensure the latest Keynote version is installed
  community.general.mas:
    id: "{{ mas_applications }}"
    state: latest

- name: Upgrade applications
  ansible.builtin.command: xcodebuild -license accept
  become: yes
  changed_when: false

- name: Upgrade all installed Mac App Store apps
  community.general.mas:
    upgrade_all: yes
