---
- name: Register fish shell path
  ansible.builtin.command: which fish
  register: fish_path
  changed_when: false

- name: Register zsh shell path
  ansible.builtin.command: which zsh
  register: zsh_path
  changed_when: false

- name: Ensure candiate shell for fish, zsh
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ item }}"
  loop:
    - "{{ fish_path.stdout }}"
    - "{{ zsh_path.stdout }}"
  become: yes

- name: Set fish to Login shell
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ fish_path.stdout }}"
  become: yes

- name: Create directory for fisherman
  ansible.builtin.file:
    path: ~/.config/fish/functions
    state: directory

- name: Install fisherman
  ansible.builtin.get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish

- name: Install plugins by fisherman
  ansible.builtin.command: fish -lc "fisher install decors/fish-ghq jethrokuan/fzf jethrokuan/z franciscolourenco/done"

- name: Apply starship
  ansible.builtin.lineinfile:
    path: ~/.config/fish/config.fish
    line: "{{ item }}"
    create: true
  loop:
    - set -x PATH /opt/homebrew/bin $PATH
    - starship init fish | source

- name: change to fish shell
  ansible.builtin.command: "{{ fish_path.stdout }}"

- name: get powerline
  ansible.builtin.command: ghq get powerline/fonts

- name: install powerline
  ansible.builtin.command: ~/ghq/github.com/powerline/fonts/install.sh