---
- name: Ensure change shell for fish
  lineinfile:
    dest: /etc/shells
    line: /usr/local/bin/fish
  become: yes

- name: Current shell
  shell: echo $SHELL
  register: current_shell
  changed_when: false

- name: Login shell fish
  shell: chsh -s /usr/local/bin/fish
  when: current_shell != '/usr/local/bin/fish'

- name: Create ~/.config/fish/functions for install fisherman
  file:
    path: ~/.config/fish/functions
    state: directory

- name: Install fisherman
  get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish

- name: Install theme(bobthefish) by fisherman
  shell: fish -lc "fisher omf/theme-bobthefish"
  args:
    creates: ~/.config/fisherman/default

- name: Install plugins by fisherman
  shell: fish -lc "fisher fnm z fzf bd ghq"
