---
- name: Mac Provisioning
  hosts: local
  become: no
  # pre_tasks:
  #   - stat: path=~/.ssh
  #     register: ssh
  roles:
    # App Install
    - homebrew



    # Other
    # - {
    #   role: ssh,
    #   when: not ssh.stat.exists
    # }