---
- name: Mac Provisioning
  hosts: local
  become: no
  pre_tasks:
    - stat: path=~/.ssh
      register: ssh
  roles:
    # App Install
    - homebrew
    - homebrew-cask
    - mas

    Configurations
    - osx-defaults
    - git
    - fish



    # SSH
    - {
      role: SSH,
      when: not ssh.stat.exists
    }